# Generated by Django 3.1.7 on 2021-04-02 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crudapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='log',
            new_name='method',
        ),
        migrations.AddField(
            model_name='log',
            name='request',
            field=models.TextField(blank=True, null=True),
        ),
    ]
