# Generated by Django 3.1.7 on 2021-04-02 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crudapp', '0002_auto_20210402_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='response',
            field=models.TextField(blank=True, null=True),
        ),
    ]
