# Generated by Django 3.1.7 on 2021-04-07 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Crudapp', '0003_log_response'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Log',
        ),
    ]
